apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cosmer
spec:
  selector:
    matchLabels:
      type: local
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-cosmer